In [1]:
pip install skyfield pandas openpyxl

Collecting skyfield
  Downloading skyfield-1.53-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.11/dist-packages (3.1.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from skyfield) (2025.4.26)
Collecting jplephem>=2.13 (from skyfield)
  Downloading jplephem-2.22-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from skyfield) (2.0.2)
Collecting sgp4>=2.13 (from skyfield)
  Downloading sgp4-2.24-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.11/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading skyfield-1.53-py3-none-any.whl (366 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 367.0/367.0 kB 6.2 MB/s eta 0:00:00
Downloading jplephem-2.22-py3-none-any.whl (47 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.2/47.2 kB 1.1 MB/s eta 0:00:00
Downloading sgp4-2.24-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (234 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 234.5/234.5 kB 10.5 MB/s eta 0:00:00
Installing collected packages: sgp4, jplephem, skyfield
Successfully installed jplephem-2.22 sgp4-2.24 skyfield-1.53

In [2]:
from datetime import datetime, timedelta
import pandas as pd
from skyfield.api import load
from skyfield.api import Topos

# Load ephemeris data
eph = load('de421.bsp')
ts = load.timescale()

# Planets
planets = {
    'Jupiter': eph['jupiter barycenter'],
    'Saturn': eph['saturn barycenter'],
    'Mars': eph['mars'],
    'Neptune': eph['neptune barycenter'],
    'Uranus': eph['uranus barycenter']
}

# Dates
end_date = datetime.utcnow().date()
start_date = end_date - timedelta(days=365 * 20)
dates = [start_date + timedelta(days=i) for i in range((end_date - start_date).days + 1)]

# Observer location for geocentric
earth = eph['earth']

# Prepare data storage
data = []

for date in dates:
    t = ts.utc(date.year, date.month, date.day)

    row = {'Date': date}
    for name, planet in planets.items():
        # Geocentric: position from Earth
        astrometric = earth.at(t).observe(planet).apparent()
        geo_lon, _, _ = astrometric.ecliptic_latlon()
        row[f'{name}_Geo'] = geo_lon.degrees

        # Heliocentric: position from Sun
        heliocentric = eph['sun'].at(t).observe(planet)
        helio_lon, _, _ = heliocentric.ecliptic_latlon()
        row[f'{name}_Helio'] = helio_lon.degrees

    data.append(row)

# Convert to DataFrame
df = pd.DataFrame(data)

# Save to Excel
output_path = "planetary_degrees_20years.xlsx"
df.to_excel(output_path, index=False)

output_path

[#################################] 100% de421.bsp

'planetary_degrees_20years.xlsx'

In [4]:
# Re-import needed packages after code execution state reset
from datetime import datetime, timedelta
import pandas as pd
from skyfield.api import load

# Load ephemeris data
eph = load('de421.bsp')
ts = load.timescale()

# Planets
planets = {
    'Jupiter': eph['jupiter barycenter'],
    'Saturn': eph['saturn barycenter'],
    'Mars': eph['mars'],
    'Neptune': eph['neptune barycenter'],
    'Uranus': eph['uranus barycenter']
}

# Dates: Every day at 6am for 30 years
end_date = datetime.utcnow().date()
start_date = end_date - timedelta(days=365 * 30)
dates = [start_date + timedelta(days=i) for i in range((end_date - start_date).days + 1)]

# Observer location for geocentric
earth = eph['earth']

# Prepare data storage
data = []

for date in dates:
    t = ts.utc(date.year, date.month, date.day, 6)  # 6 AM UTC

    row = {'Date': date}
    for name, planet in planets.items():
        # Geocentric: position from Earth
        astrometric = earth.at(t).observe(planet).apparent()
        geo_lon, _, _ = astrometric.ecliptic_latlon()
        row[f'{name}_Geo'] = geo_lon.degrees

        # Heliocentric: position from Sun
        heliocentric = eph['sun'].at(t).observe(planet)
        helio_lon, _, _ = heliocentric.ecliptic_latlon()
        row[f'{name}_Helio'] = helio_lon.degrees

    data.append(row)

# Convert to DataFrame
df = pd.DataFrame(data)

# Save to Excel
output_path = "planetary_degrees_30years_6am.xlsx"
df.to_excel(output_path, index=False)

output_path

'planetary_degrees_30years_6am.xlsx'

In [5]:
df

,Date,Jupiter_Geo,Jupiter_Helio,Saturn_Geo,Saturn_Helio,Mars_Geo,Mars_Helio,Neptune_Geo,Neptune_Helio,Uranus_Geo,Uranus_Helio
0,1995-06-03,0.799511,0.647615,-1.988250,-2.020054,1.286678,1.129100,0.555623,0.541837,-0.555995,-0.536474
1,1995-06-04,0.797502,0.646056,-1.992325,-2.020881,1.265546,1.117455,0.555662,0.541662,-0.556471,-0.536582
2,1995-06-05,0.795438,0.644496,-1.996422,-2.021708,1.244598,1.105728,0.555696,0.541487,-0.556941,-0.536690
3,1995-06-06,0.793320,0.642934,-2.000541,-2.022534,1.223833,1.093920,0.555727,0.541312,-0.557406,-0.536798
4,1995-06-07,0.791148,0.641371,-2.004680,-2.023360,1.203247,1.082031,0.555753,0.541136,-0.557865,-0.536906
...,...,...,...,...,...,...,...,...,...,...,...
10946,2025-05-22,-0.199613,-0.234164,-2.070077,-2.164797,1.608840,1.564651,-1.291151,-1.312634,-0.215252,-0.226218
10947,2025-05-23,-0.197777,-0.232254,-2.073727,-2.165504,1.592161,1.557064,-1.291891,-1.312760,-0.215122,-0.226072
10948,2025-05-24,-0.195950,-0.230344,-2.077412,-2.166212,1.575588,1.549382,-1.292639,-1.312885,-0.214996,-0.225926
10949,2025-05-25,-0.194133,-0.228433,-2.081132,-2.166918,1.559119,1.541606,-1.293393,-1.313011,-0.214873,-0.225780
10950,2025-05-26,-0.192327,-0.226523,-2.084886,-2.167624,1.542751,1.533734,-1.294154,-1.313136,-0.214752,-0.225634

In [ ]:
from google.colab import drive
drive.mount('/content/drive')